#!/bin/bash

#set -x
set -e
echo "=== Network configuration ==="
update-ca-certificates
systemctl disable smartd
sudo tee /etc/NetworkManager/NetworkManager.conf <<EOF
[main]
plugins=ifupdown,keyfile

[ifupdown]
managed=true
EOF
sudo chmod 644 /etc/NetworkManager/NetworkManager.conf
systemctl enable NetworkManager

echo "=== DNS configuration ==="
sudo tee /etc/resolv.conf <<EOF
# Generated by quel_tale and not systemd
nameserver 1.1.1.1
nameserver 8.8.8.8
EOF

sudo tee /etc/systemd/resolved.conf <<EOF
#  This file is not really part of systemd. It was edited by hand.
#
# Use 'systemd-analyze cat-config systemd/resolved.conf' to display the full config.
#
# See resolved.conf(5) for details.

[Resolve]
# Some examples of DNS servers which may be used for DNS= and FallbackDNS=:
# Cloudflare: 1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001
# Google:     8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844
# Quad9:      9.9.9.9 2620:fe::fe
DNS=1.1.1.1 8.8.8.8
FallbackDNS=1.0.0.1 8.8.4.4 9.9.9.9 2606:4700:4700::1111 2620:fe::10 2001:4860:4860::8888
Domains=lab.weeeopen.it
DNSSEC=no
DNSOverTLS=opportunistic
#MulticastDNS=yes
#LLMNR=yes
#Cache=yes
#CacheFromLocalhost=no
#DNSStubListener=yes
#DNSStubListenerExtra=
#ReadEtcHosts=yes
#ResolveUnicastSingleLabel=no
EOF
rm -f /var/run/NetworkManager/* 2>/dev/null

echo "=== NTP configuration ==="
systemctl enable systemd-timesyncd
rm -f /etc/localtime
ln -s /usr/share/zoneinfo/Europe/Rome /etc/localtime
