version: "3"

services:
    miso:
        hostname: weeedebian
        container_name: miso
        tty: true
        volumes:
            - ./build:/build:rwz
            - ./weeedebian:/weeedebian:roz
        environment:
            - MISO_ARCH=i386
            - VERSION=1.1.1
            - MISO_CHROOT_SCRIPT=/weeedebian/martello.sh
            - MISO_BUILD_DIR=/build
            - MISO_HOSTNAME=weeedebian
            - MISO_ROOTPASSWD=asd
            - MISO_USERNAME=weee
            - MISO_USERPASSWD=asd
        build: .