services:
    miso:
        container_name: miso
        build: .
        hostname: weeedebian
        volumes:
            - ./build:/miso/build:rwz
            - ./weeedebian:/miso/weeedebian:roz
            - ./chroot_scripts:/miso/chroot_scripts:roz
        tty: true
        stdin_open: true
        privileged: true
