services:
    miso:
        hostname: weeedebian
        container_name: miso
        tty: true
        privileged: true
        volumes:
            - ./build:/miso/build:rwz
            - ./weeedebian:/miso/weeedebian:roz
            - ./chroot_scripts:/miso/chroot_scripts:roz
            - /proc:/proc:rwz
        build: .
        stdin_open: true
