version: "3"

services:
    miso:
        container_name: miso
        stdin_open: true
        tty: true
        volumes:
            - ./build:/build:rw
            - ./weeedebian:/weeedebian:ro
        environment:
            - MISO_CHROOT_SCRIPT=/weeedebian/martello.sh
            - MISO_HOSTNAME=weeedebian
            - MISO_ROOTPASSWD=asd
            - MISO_USERNAME=weee
            - MISO_USERPASSWD=asd
            - MISO_ARCH=amd64
        build: .