on: push
name: build iso
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  build_iso:
    name: Build weeedebian ISO
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v4
        - name: Install dependencies
          run: sudo apt-get update && sudo apt-get install -y debootstrap squashfs-tools dosfstools xorriso isolinux syslinux-efi grub-pc-bin grub-efi-amd64-bin mtools debian-archive-keyring isolinux syslinux
        - name: Dotenv Action
          uses: falti/dotenv-action@v1.1
          id: dotenv
          with:
            export-variables: true
        - name: Set T.A.R.A.L.L.O. Token
          uses: "DamianReeves/write-file-action@master"
          with:
            path: weeedebian/env.txt
            write-mode: append
            contents: ${{ secrets.TARALLO_TOKEN }}
        - name: build amd64
          env:
            MISO_ARCH: amd64
          run: ./miso.sh
          shell: bash
        - name: build i386
          env:
            MISO_ARCH: i386
          run: ./miso.sh
          shell: bash
        - uses: ncipollo/release-action@v1
          with:
            artifacts: "./build/*/*.iso"
            prerelease: true
            tag: v${{ steps.dotenv.outputs.version }}