on: push
name: build iso
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  build_iso:
    name: Build weeedebian ISO
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v4
        - name: Install dependencies
          run: sudo apt-get update && sudo apt-get install -y debootstrap squashfs-tools dosfstools xorriso isolinux syslinux-efi grub-pc-bin grub-efi-amd64-bin mtools debian-archive-keyring isolinux syslinux
        - name: Dotenv Action
          uses: falti/dotenv-action@v1.1
          id: dotenv
          with:
            export-variables: true
        - name: build amd64
          env:
            MISO_ARCH: amd64
          run: ./miso.sh
          shell: bash
        - name: build i386
          env:
            MISO_ARCH: i386
          run: ./miso.sh
          shell: bash
        - name: release
          uses: actions/create-release@v1
          id: create_release
          with:
            draft: true
            prerelease: false
            release_name: v${{ steps.dotenv.outputs.version }}
            tag_name: ${{ github.ref }}
            # body_path: CHANGELOG.md
          env:
            GITHUB_TOKEN: ${{ github.token }}
        - name: upload am64 artifact
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ github.token }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./build/weeedebian-amd64/weeedebian-amd64.iso
            asset_name: weeedebian-amd64.iso
            asset_content_type: application/gzip
        - name: upload i386 artifact
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ github.token }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./build/weeedebian-i386/weeedebian-i386.iso
            asset_name: weeedebian-i386.iso
            asset_content_type: application/gzip