on: push
name: build iso
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  build_iso:
    name: Build weeedebian ISO
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v4
        - name: Install dependencies
          run: sudo apt-get update && sudo apt-get install -y debootstrap squashfs-tools dosfstools xorriso isolinux syslinux-efi grub-pc-bin grub-efi-amd64-bin mtools debian-archive-keyring isolinux syslinux
        - name: Dotenv Action
          uses: falti/dotenv-action@v1.1
          id: dotenv
          with:
            export-variables: true
        - name: build amd64
          env:
            MISO_ARCH: amd64
          run: ./miso.sh
          shell: bash
        - name: build i386
          env:
            MISO_ARCH: i386
          run: ./miso.sh
          shell: bash
        - name: release
          uses: "marvinpinto/action-automatic-releases@latest"
          id: create_release
          with:
            draft: true
            prerelease: false
            automatic_release_tag: v${{ steps.dotenv.outputs.version }}
            repo_token: ${{ github.token }}
            files: |
              ./build/weeedebian-amd64/weeedebian-amd64.iso
              ./build/weeedebian-i386/weeedebian-i386.iso